# Generated by Django 5.2.3 on 2025-06-27 13:17

import localflavor.in_.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="state",
            field=localflavor.in_.models.INStateField(default="HR", max_length=2),
        ),
        migrations.AddField(
            model_name="location",
            name="zip_code",
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name="location",
            name="address_1",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
